# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8456b6b07e1cfbf27f5f481f5b81c05be35516dac76d1667dd28082347c2ac42f6bd4b7470f3ff2b29b6aa3c7fbfae5408255e2cb6d814dcde22b5a1ec4797d

test:
  secret_key_base: fc1c12194d966d12851605ea80b8543af4ab3836ab28df7e98835ac81da458b06d7fa5a497aacc9b7ab6b34e91834cde42d60955676d2e97ad37075d5e5ec690

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
